<a href="https://colab.research.google.com/github/pb-roshith/numpy-essential/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30])

In [3]:
a

array([10, 20, 30])

In [4]:
a[0]

np.int64(10)

In [5]:
a[-1]

np.int64(30)

In [6]:
a[0]=11

In [7]:
a

array([11, 20, 30])

In [9]:
a[:2]

array([11, 20])

In [11]:
a[1:]

array([20, 30])

In [12]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
x.ndim

2

In [14]:
a.dtype

dtype('int64')

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
np.zeros((2,4,5), dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((2,6), dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [24]:
np.ones((3,4,2), dtype=int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [25]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
np.empty((3,4))

array([[8.4826831e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [28]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [33]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [35]:
np.linspace(3,61,9, dtype=int)

array([ 3, 10, 17, 24, 32, 39, 46, 53, 61])

In [36]:
arr = np.array([20,30,10,60,40])

In [38]:
np.sort(arr)

array([10, 20, 30, 40, 60])

In [39]:
np.argsort(arr)

array([2, 0, 1, 4, 3])

In [55]:
x = np.array([34,4,45,32,40,65,54,39,44,41,89,50,2,88,82])
y = np.array([10,20,30])

In [56]:
np.concatenate((x,y))

array([34,  4, 45, 32, 40, 65, 54, 39, 44, 41, 89, 50,  2, 88, 82, 10, 20,
       30])

In [57]:
x.reshape(3,5)

array([[34,  4, 45, 32, 40],
       [65, 54, 39, 44, 41],
       [89, 50,  2, 88, 82]])

In [67]:
x[1:]

array([ 4, 45, 32, 40, 65, 54, 39, 44, 41, 89, 50,  2, 88, 82])

In [68]:
x<50

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True, False, False,  True, False, False])

In [69]:
x==4

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [70]:
x[x<10]

array([4, 2])

In [71]:
x[(x<90) & (x>80)]

array([89, 88, 82])

In [78]:
x[(x>50) | (x==4)]

array([ 4, 65, 54, 89, 88, 82])

In [79]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [80]:
r = np.vstack((a,b))
r

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
r1 = np.hstack((a,b))
r1

array([1, 2, 3, 4, 5, 6])

In [82]:
a = np.array([[1], [2], [3]])  # Shape (3, 1)
b = np.array([[4], [5], [6]])  # Shape (3, 1)

result = np.hstack((a, b))

print(result)


[[1 4]
 [2 5]
 [3 6]]


In [83]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [86]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [87]:
np.hsplit(x,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [88]:
np.hsplit(x,6)

[array([[ 1,  2],
        [13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8],
        [19, 20]]),
 array([[ 9, 10],
        [21, 22]]),
 array([[11, 12],
        [23, 24]])]

In [101]:
p = np.arange(1,15)
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [102]:
b = p

In [103]:
p[0]=100

In [104]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14])

In [106]:
e = p.copy()

In [107]:
e

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14])

In [110]:
p[1]=200
p

array([100, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14])

In [111]:
e

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14])

In [115]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [116]:
a+b

array([5, 7, 9])

In [117]:
a-b

array([-3, -3, -3])

In [118]:
a*b

array([ 4, 10, 18])

In [119]:
a/b

array([0.25, 0.4 , 0.5 ])

In [121]:
a**b

array([  1,  32, 729])

In [122]:
a.sum()

np.int64(6)

In [123]:
a.max()

np.int64(3)

In [124]:
a.min()

np.int64(1)

In [125]:
a.mean()

np.float64(2.0)

In [127]:
a.std()

np.float64(0.816496580927726)

In [128]:
k = np.array([1,2,50,90])
k.std()

np.float64(37.05654463114444)

In [131]:
a = np.array([[1, 2],
              [3, 4]])

# Product of all elements
print(np.prod(a))         # 1*2*3*4 = 24

# Product along axis=0 (columns)
print(np.prod(a, axis=0)) # [1*3, 2*4] = [3, 8]

# Product along axis=1 (rows)
print(np.prod(a, axis=1)) # [1*2, 3*4] = [2, 12]


24
[3 8]
[ 2 12]


In [132]:
np.random.rand(5)

array([0.0199797 , 0.15118273, 0.91940502, 0.16626449, 0.10610635])

In [133]:
np.random.randint(10,20,5)

array([17, 12, 13, 15, 19])

In [136]:
d = np.arange(1,13).reshape(3,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [137]:
d.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [140]:
re = np.flip(d, axis=0)
re

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [141]:
re = np.flip(d, axis=1)
re

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [142]:
d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [145]:
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [143]:
re.ravel()

array([ 4,  3,  2,  1,  8,  7,  6,  5, 12, 11, 10,  9])

In [146]:
re

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [147]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [150]:
help(min)

Help on built-in function min in module builtins:

min(...)
    min(iterable, *[, default=obj, key=func]) -> value
    min(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its smallest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the smallest argument.



In [151]:
help(np.sort)

Help on _ArrayFunctionDispatcher in module numpy:

sort(a, axis=-1, kind=None, order=None, *, stable=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and,
        in general, the actual implementation will vary with data type.
        The 'mergesort' option is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compar

In [152]:
help(np.hstack)

Help on _ArrayFunctionDispatcher in module numpy:

hstack(tup, *, dtype=None, casting='same_kind')
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versio